# Usando imagem base recomendada para o Node.js
FROM node:14

# Definindo o diretório de trabalho
WORKDIR /app

# Copiando o package.json e package-lock.json e instalando dependências
COPY package*.json ./
RUN npm install

# Copiando o código do backend para o contêiner
COPY . .

# Expondo a porta que o backend utilizará
EXPOSE 5000

# Comando para iniciar o servidor
CMD ["node", "server.js"]
