jobs:
  build-and-test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build frontend Docker image
        run: docker build -t my-frontend ./frontend

      - name: Run frontend tests
        run: docker run my-frontend npm test

      # Exibe o log de erro se o build falhar
      - name: Show npm log if build fails
        if: failure()
        run: cat /root/.npm/_logs/*.log

  build-and-test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build backend Docker image
        run: docker build -t my-backend ./backend

      - name: Run backend tests
        run: docker run my-backend npm test

      # Exibe o log de erro se o build falhar
      - name: Show npm log if build fails
        if: failure()
        run: cat /root/.npm/_logs/*.log